/* root */
export const SHOW_PAGE_LOADING = 'SHOW_PAGE_LOADING';
export const HIDE_PAGE_LOADING = 'HIDE_PAGE_LOADING';
export const PROVINCE = 'PROVINCE';
export const PERMISSIONS = 'PERMISSIONS';
export const USER_ROLE_LIST = 'USER_ROLE_LIST';
export const ROUTE_CHANGE = 'ROUTE_CHANGE';
export const CURRENT_USER_GET_INFO = 'CURRENT_USER_GET_INFO';
export const ADD_ROUTES = 'ADD_ROUTES';
export const STATIC_DATA = 'STATIC_DATA';
export const FIRST_PAGE = 'FIRST_PAGE';

/* login */
export const SET_LOGIN_USER = 'SET_LOGIN_USER';
export const LOG_OUT = 'LOG_OUT';

/* system */
export const ROLE_LIST = 'ROLE_LIST';
export const ROLE_INIT_FORM = 'ROLE_INIT_FORM';
export const ROLE_GET_INFO = 'ROLE_GET_INFO';
export const USER_GET_LIST = 'USER_GET_LIST';
export const USER_INIT_FORM = 'USER_INIT_FORM';
export const USER_GET_INFO = 'USER_GET_INFO';
export const SYSTEM_QUERY_REGION = 'SYSTEM_QUERY_REGION';
export const ROLE_REDIRECT_USER_CREATE = 'ROLE_REDIRECT_USER_CREATE';

/* data-analysis */
export const CLIENT_GET = 'CLIENT_GET';
export const ACTIVE_GET_DAILY_USER = 'ACTIVE_GET_DAILY_USER';
export const ACTIVE_GET_MEMBERS = 'ACTIVE_GET_MEMBERS';
export const TREND_GET_LIST = 'TREND_GET_LIST';
export const TREND_GET_NEW_MEMBERS = 'TREND_GET_NEW_MEMBERS';
export const ACTIVE_UPDATE_TREND = 'ACTIVE_UPDATE_TREND';
export const PROVINCE_GET_MAP_JSON = 'PROVINCE_GET_MAP_JSON';
export const PROVINCE_GET_USER = 'PROVINCE_GET_USER';
export const RETENTION_GET_USER = 'RETENTION_GET_USER';
export const RETENTION_GET_TREND_LIST = 'RETENTION_GET_TREND_LIST';
export const RETENTION_UPDATE_TREND_LIST = 'RETENTION_UPDATE_TREND_LIST';
export const ACTIVE_INIT_DATE = 'ACTIVE_INIT_DATE';
export const PROVINCER_USER_INIT_DATE = 'PROVINCER_USER_INIT_DATE';

/* task */
export const TASK_QUERY_LIST = 'TASK_QUERY_LIST';
export const TASK_GET_DETAIL = 'TASK_GET_DETAIL';
export const SET_PUSH_LIST = 'SET_PUSH_LIST';
export const SET_TODO_LIST = 'SET_TODO_LIST';

/* order */
export const ORDER_GET_LIST = 'ORDER_GET_LIST';
export const ORDER_OV_SIGN_HANDLE = 'ORDER_OV_SIGN_HANDLE';
export const ORDER_CREATE = 'ORDER_CREATE';
export const ORDER_QUERY_ORGANIZE_ADDRESS = 'ORDER_QUERY_ORGANIZE_ADDRESS';
export const ORDER_GET_DETAIL = 'ORDER_GET_DETAIL';
export const ORDER_CM_GET_LIST = 'ORDER_CM_GET_LIST';
export const ORDER_HT_GET_LIST = 'ORDER_HT_GET_LIST';
export const ORDER_QUERY_ASSIGN_HANDLER = 'ORDER_QUERY_ASSIGN_HANDLER';
export const ORDER_GET_HANDLE_TASK_DETAIL = 'ORDER_GET_HANDLE_TASK_DETAIL';
export const ORDER_SUBMIT_ORDER_ROW = 'ORDER_SUBMIT_ORDER_ROW';
export const ORDER_DELETE_ORDER_ROW = 'ORDER_DELETE_ORDER_ROW';
export const ORDER_UPDATE_PROCESS_ID = 'ORDER_UPDATE_PROCESS_ID';
export const ORDER_OVERVIEW_GET_DETAIL = 'ORDER_OVERVIEW_GET_DETAIL';
export const ORDER_GET_PROCESS_LIST = 'ORDER_GET_PROCESS_LIST';
export const ORDER_UPDATE_CREATE = 'ORDER_UPDATE_CREATE';
export const ORDER_GET_EDIT = 'ORDER_GET_EDIT';
export const ORDER_QUERY_PRODUCT_NAME = 'ORDER_QUERY_PRODUCT_NAME';
export const ORDER_SUBMIT_ASSIGN_BUTTON_STATUS = 'ORDER_SUBMIT_ASSIGN_BUTTON_STATUS';
export const ORDER_GET_HAS_SIGNED_FILE = 'ORDER_GET_HAS_SIGNED_FILE';
export const ORDER_OVERVIEW_PAGE_CHANGE = 'ORDER_OVERVIEW_PAGE_CHANGE';
export const ORDER_CM_PAGE_CHANGE = 'ORDER_CM_PAGE_CHANGE';
export const ORDER_HT_PAGE_CHANGE = 'ORDER_HT_PAGE_CHANGE';
export const ORDER_LAST_PROCESS_INFO = 'ORDER_LAST_PROCESS_INFO';

/* group_customer */
export const GROUP_CUSTOMER_INIT_FORM = 'GROUP_CUSTOMER_INIT_FORM';
export const GROUP_CUSTOMER_GET_LIST = 'GROUP_CUSTOMER_GET_LIST';
export const GROUP_CUSTOMER_GET_INFO = 'GROUP_CUSTOMER_GET_INFO';
export const GROUP_CUSTOMER_MANAGERS = 'GROUP_CUSTOMER_MANAGERS';
export const GROUP_CUSTOMER_DETAIL = 'GROUP_CUSTOMER_DETAIL';
export const GROUP_CUSTOMER_SUBSCRIBE_PRODUCTS = 'GROUP_CUSTOMER_SUBSCRIBE_PRODUCTS';
export const GROUP_CUSTOMER_PROCESSES = 'GROUP_CUSTOMER_PROCESSES';

/* product */
export const PRODUCT_LIST = 'PRODUCT_LIST';
export const PRODUCT_CREAT_LIST = 'PRODUCT_CREAT_LIST';
export const PRODUCT_DETAIL = 'PRODUCT_DETAIL';
export const COMPOSED_PRODUCT = 'COMPOSED_PRODUCT';
export const DETAIL_SALE = 'DETAIL_SALE';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const SAVE_BASE_INFO = 'SAVE_BASE_INFO';
export const SAVE_SALE_STEP = 'SAVE_SALE_STEP';
/* business */
export const COOPERATION_GROUP = 'COOPERATION_GROUP';
export const BUSINESS_OPPORTUNITY_LIST = 'BUSINESS_OPPORTUNITY_LIST';
export const BUSINESS_DETAIL = 'BUSINESS_DETAIL';
export const OFFICE_ADDRESS = 'OFFICE_ADDRESS';
export const SUBMIT_BUSINESS_STATUS = 'SUBMIT_BUSINESS_STATUS';
export const GROUP_ASSOCIATION_STATUS = 'GROUP_ASSOCIATION_STATUS';
export const DEL_BUSINESS_STATUS = 'DEL_BUSINESS_STATUS';
export const DESIGNATE_PERSON = 'DESIGNATE_PERSON';
export const REMIND_PERSON = 'REMIND_PERSON';
export const SUBMIT_BUSINESS_SEND_STATUS = 'SUBMIT_BUSINESS_SEND_STATUS';
export const SUBMIT_BUSINESS_CANCEL_STATUS = 'SUBMIT_BUSINESS_CANCEL_STATUS';
export const SAVE_BUSINESS_DRAFT_STATUS = 'SAVE_BUSINESS_DRAFT_STATUS';
export const SAVE_BUSINESS_ORDER = 'SAVE_BUSINESS_ORDER';
export const SAVE_BUSINESS_ORDER_DRAFT = 'SAVE_BUSINESS_ORDER_DRAFT';
export const MY_BUSINESS_LIST = 'MY_BUSINESS_LIST';
export const BUSINESS_TASK_LIST = 'BUSINESS_TASK_LIST';
export const TRANSFOR_ORDER_DETAIL = 'TRANSFOR_ORDER_DETAIL';
export const SUBMIT_BUSINESS_DRAFT_STATUS = 'SUBMIT_BUSINESS_DRAFT_STATUS';
export const EDIT_BUSINESS_DETAIL_STATUS = 'EDIT_BUSINESS_DETAIL_STATUS';
export const PRODUCT_NAME_CODE = 'PRODUCT_NAME_CODE';
export const EDIT_BUSINESS_DETAIL_APPROVE_STATUS = 'EDIT_BUSINESS_DETAIL_APPROVE_STATUS';
export const QUERY_TASK = 'QUERY_TASK';

/* requirement */
export const REQUIREMENT_GET_LIST = 'REQUIREMENT_GET_LIST';
export const REQUIREMENT_GET_INFO = 'REQUIREMENT_GET_INFO';
export const REQUIREMENT_TASK_LIST = 'REQUIREMENT_TASK_LIST';
export const REQUIREMENT_PROCESSORS = 'REQUIREMENT_PROCESSORS';
export const REQUIREMENT_CREATE_PROCESSORS = 'REQUIREMENT_CREATE_PROCESSORS';

/* visit */
export const MY_VISIT_MANAGE_LIST = 'MY_VISIT_MANAGE_LIST';
export const CREATE_VISIT_DATA = 'CREATE_VISIT_DATA';
export const APPOINT_VISIT_LIST = 'APPOINT_VISIT_LIST';
export const VISIT_APPOINT_DETAIL = 'VISIT_APPOINT_DETAIL';
export const REGION_MANAGE_LIST = 'REGION_MANAGE_LIST';
export const GET_PROCESSOR_LIST = 'GET_PROCESSOR_LIST';
export const HANDLE_VISIT_MANAGE_LIST = 'HANDLE_VISIT_MANAGE_LIST';
export const REGISTER_LIST = 'REGISTER_LIST';
export const VISIT_DETAIL = 'VISIT_DETAIL';
export const APPOINT_CREATE = 'APPOINT_CREATE';

/* dashboard */
export const HOME_MODULE = 'HOME_MODULE';
export const HOME_MODULE_FROM_MENU = 'HOME_MODULE_FROM_MENU';
export const UPDATE_HOME_MODULE_STATUS = 'UPDATE_HOME_MODULE_STATUS';
export const HOME_BUSINESS_LIST = 'HOME_BUSINESS_LIST';
export const HOME_ORDER_LIST = 'HOME_ORDER_LIST';
export const HOME_QUERY_TASK_INFO_ORANGIZE = 'HOME_QUERY_TASK_INFO_ORANGIZE';
export const HOME_QUERY_TASK_INFO_ORDER = 'HOME_QUERY_TASK_INFO_ORDER';
export const HOME_QUERY_TASK_INFO_BUSINESS = 'HOME_QUERY_TASK_INFO_BUSINESS';
export const HOME_QUERY_TASK_INFO_REQUIRE = 'HOME_QUERY_TASK_INFO_REQUIRE';
export const HOME_QUERY_TASK_INFO_VISIT = 'HOME_QUERY_TASK_INFO_VISIT';
export const HOME_QUERY_ORGANIZE_INFO = 'HOME_QUERY_ORGANIZE_INFO';

/* data-extraction */
export const DATA_EXTRACTION_DOWMLOAD = 'DATA_EXTRACTION_DOWMLOAD';
