/* root */
export const DEMO_LIST = 'DEMO_LIST';
export const SHOW_PAGE_LOADING = 'SHOW_PAGE_LOADING';
export const HIDE_PAGE_LOADING = 'HIDE_PAGE_LOADING';
export const PROVINCE = 'PROVINCE';
export const PERMISSIONS = 'PERMISSIONS';
export const USER_ROLE_LIST = 'USER_ROLE_LIST';
export const ROUTE_CHANGE = 'ROUTE_CHANGE';
export const CURRENT_USER_GET_INFO = 'CURRENT_USER_GET_INFO';
export const ADD_ROUTES = 'ADD_ROUTES';

/* login */
export const SET_LOGIN_USER = 'SET_LOGIN_USER';
export const LOG_OUT = 'LOG_OUT';

/* system */
export const ROLE_LIST = 'ROLE_LIST';
export const ROLE_INIT_FORM = 'ROLE_INIT_FORM';
export const ROLE_GET_INFO = 'ROLE_GET_INFO';
export const USER_GET_LIST = 'USER_GET_LIST';
export const USER_INIT_FORM = 'USER_INIT_FORM';
export const USER_GET_INFO = 'USER_GET_INFO';

/* data-analysis */
export const CLIENT_GET = 'CLIENT_GET';
export const ACTIVE_GET_DAILY_USER = 'ACTIVE_GET_DAILY_USER';
export const ACTIVE_GET_MEMBERS = 'ACTIVE_GET_MEMBERS';
export const TREND_GET_LIST = 'TREND_GET_LIST';
export const TREND_GET_NEW_MEMBERS = 'TREND_GET_NEW_MEMBERS';
export const ACTIVE_UPDATE_TREND = 'ACTIVE_UPDATE_TREND';
export const PROVINCE_GET_MAP_JSON = 'PROVINCE_GET_MAP_JSON';
export const PROVINCE_GET_USER = 'PROVINCE_GET_USER';
export const RETENTION_GET_USER = 'RETENTION_GET_USER';
export const RETENTION_GET_TREND_LIST = 'RETENTION_GET_TREND_LIST';
export const RETENTION_UPDATE_TREND_LIST = 'RETENTION_UPDATE_TREND_LIST';
export const ACTIVE_INIT_DATE = 'ACTIVE_INIT_DATE';

/* task */
export const SET_TASK_LIST = 'SET_TASK_LIST';
export const SET_PUSH_LIST = 'SET_PUSH_LIST';
export const SET_TODO_LIST = 'SET_TODO_LIST';
